site_name: mydocs_myLibrary
site_url: http://127.0.0.1:6008
repo_url: https://github.com/mikeyarthur/mydocs_myLibrary.git
dev_addr: 127.0.0.1:6008

nav:
    - Home: ./index.md
    # - About: ./../README.md
    - Study:
        - shell:
            - Study/shell/command.md
            - Study/shell/sh.md
        - git:
            - Study/git/git_overview.md
            - Study/git/git_gitignore.md
            - Study/git/git_stash.md
        - Obsidian:
            - Study/Obsidian/Mikey的小目标.md
            - Study/Obsidian/Obsidian_demo.md
    - Project:
        - ft:
            - fp:
                - Project/ft/fp/fp_overview.md
                - Project/ft/fp/fp_event_thread.md
            - tp:
                - Project/ft/tp/tp_overview.md

theme:
    # name: mkdocs
    # name: readthedocs
    #name: windmill                 # pip install mkdocs-windmill
    #custom_dir: custom_theme
    #
    # https://zhuanlan.zhihu.com/p/383582472
    #
    name: 'material'                # pip install mkdocs-material
    language: 'zh'                  # 配置语言
    palette:                        # 颜色
        primary: 'light blue'
        accent: 'indigo'
    feature:
        tabs: true                  # 横向导航

plugins:
    - search
    #- pdf-export                   #这个插件还有点问题，没有更新

markdown_extensions:
    #- smarty
    #- toc:
    #    permalink: True
    #- sane_lists
    #
    # https://zhuanlan.zhihu.com/p/383582472
    #
    - admonition                    # 提示块
    - footnotes                     # 脚注
    - meta                          # 定义元数据，通过文章上下文控制，如disqus
    - pymdownx.caret                # 下划线上标
    - pymdownx.tilde                # 删除线下标
    - pymdownx.critic               # 增加删除修改高亮注释，可修饰行内或段落
    - pymdownx.details              # 提示块可折叠
    - pymdownx.inlinehilite         # 行内代码高亮
    - pymdownx.mark                 # 文本高亮
    - pymdownx.smartsymbols         # 符号转换
    - pymdownx.superfences          # 代码嵌套在列表里
    - codehilite:                   # 代码高亮，显示行号
        guess_lang: false
        linenums: true
    - toc:                          # 锚点
        permalink: true
    - pymdownx.arithmatex           # 数学公式
    - pymdownx.betterem:            # 对加粗和斜体更好的检测
        smart_enable: all
    - pymdownx.emoji:               # 表情
        emoji_generator: !!python/name:pymdownx.emoji.to_svg
    - pymdownx.magiclink            # 自动识别超链接
    - pymdownx.tasklist:            # 复选框checklist
        custom_checkbox: true

