site_name: mydocs_myLibrary
site_url: http://127.0.0.1:6008
repo_url: https://github.com/mikeyarthur/mydocs_myLibrary.git
dev_addr: 127.0.0.1:6008

nav:
    - Home: ./index.md
    # - About: ./../README.md
    - Study:
        - Study/shell/command.md
        - Study/shell/sh.md
        - Study/git/git_overview.md
        - Study/git/git_gitignore.md
        - Study/git/git_stash.md
        - Study/Obsidian/Mikey的小目标.md
        - Study/Obsidian/Obsidian_demo.md
    - Project:
        - Project/ft/fp/fp_overview.md
        - Project/ft/tp/tp_overview.md


theme:
    # name: mkdocs
    # name: readthedocs
    name: windmill                 # pip install mkdocs-windmill
    custom_dir: custom_theme

plugins:
    - search

markdown_extensions:
    - smarty
    - toc:
        permalink: True
    - sane_lists

